Use url as source
abelsiqueira/COPIERTemplate.jl pull request #174
Opened 2024-05-29 14:22 UTC by sverhoeven

Instead of using the copier.yml from ~/.julia/** use GH url.

Fixes #146

## Related issues

Closes #

## Checklist

- [ ] I am following the [contributing guidelines](https://github.com/abelsiqueira/COPIERTemplate.jl/blob/main/docs/src/90-contributing.md)
- [ ] Tests are passing
- [ ] Lint workflow is passing
- [ ] Docs were updated and workflow is passing
- [ ] [CHANGELOG.md](https://github.com/abelsiqueira/COPIERTemplate.jl/blob/main/CHANGELOG.md) was updated

2024-05-30 10:56 UTC, abelsiqueira commented
Zenodo failures are 50x.

2024-05-30 10:59 UTC, abelsiqueira commented
@sverhoeven I'm not sure I understood your second bullet point. This is testing the generation of the template using wrapper (Julia) vs direct (copier) in two situations: using the source "URL#main", and using the source "dir of cloned/added package".

2024-05-30 10:59 UTC, abelsiqueira commented
@sverhoeven would you like to review, or should I ask @suvayu?

2024-05-30 15:08 UTC, suvayu commented
> I'm not sure I understood your second bullet point.

In the original commit the URL was hard coded, so if you opened a PR in this repo, CI would still run on a template url that points to main, not the branch in the PR.

In the test, if you are passing a fixed url (haven't looked at your commit yet), then it should be passing the url for the PR branch for the test to be correct.

2024-05-30 15:14 UTC, suvayu requested changes
The test needs to address the 2nd bullet.

2024-05-30 15:41 UTC, suvayu approved these changes

2024-05-31 08:52 UTC, abelsiqueira commented on test/runtests.jl
> +template_url = "https://github.com/abelsiqueira/COPIERTemplate.jl"
Explained offline

2024-05-31 08:53 UTC, abelsiqueira commented
Explained offline that this actually addresses the second bullet point and the PR was approved then.

2024-05-31 08:54 UTC, merged

2024-05-31 08:55 UTC, abelsiqueira commented
@allcontributors add @suvayu for review